# Prompt
# https://starship.rs/config/#prompt
# List of prompt-wide configuration options:
# Configure the format of the prompt
# format = "$all"
# Right Prompt
# right_format = "$all"
# Timeout for starship to scan files (in milliseconds)
scan_timeout = 30
# Timeout for commands executed by starship (in milliseconds)
command_timeout = 500
# Inserts blank line between shell prompts
add_newline = false

[aws]
disabled = true
symbol = "îŒ½  "

[battery]
disabled = true

[character]
disabled = false
format = "$symbol "
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ–](bold red)"
vicmd_symbol = "[V](bold green)"

[cmake]
disabled = true
#format = "via [$symbol($version )]($style)"
#version_format = "v${raw}"
#symbol = "â–³ "
#detect_extensions = []
#detect_files = ["CMakeLists.txt", "CMakeCache.txt"]
#detect_folders = []
#style = "bold blue"

[cobol]
disabled = true

[cmd_duration]
disabled = false
min_time = 1_000
show_milliseconds = true
format = "took [$duration]($style) "
style = "bold yellow"
# show_notifications = false
# min_time_to_notify = 45_000

[conda]
disabled = true
symbol = "ï„Œ "

[crystal]
disabled = true

[dart]
disabled = true
symbol = "îž˜ "

[deno]
disabled = true

[directory]
disabled = false
truncation_length = 8
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold cyan"
#read_only = "ðŸ”’"
read_only = " ï ½"
read_only_style = "red"
truncation_symbol = "â€¦/"
# repo_root_style = None
home_symbol = "~"

[docker_context]
disabled = false
format = "via [$symbol$context]($style) "
#symbol = "ðŸ³ "
symbol = "ïŒˆ "
only_with_files = true
detect_extensions = []
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
style = "blue bold"

[dotnet]
disabled = true

[elixir]
disabled = true
symbol = "î‰µ "

[elm]
disabled = true
symbol = "î˜¬ "

[env_var]
disabled = true

[erlang]
disabled = true

# https://starship.rs/config/#fill
[fill]
disabled = true
#symbol = "-"
#style = "bold green"

[gcloud]
disabled = true

[git_branch]
disabled = false
always_show_remote = false
format = "on [$symbol$branch]($style) "
#symbol = "î‚  "
symbol = "ï˜ "
style = "bold purple"
truncation_length = 13
truncation_symbol = "â€¦"
only_attached = false

[git_commit]
disabled = false
commit_hash_length = 7
format = "[\\($hash$tag\\)]($style) "
style = "bold green"
only_detached = true
tag_disabled = false
tag_symbol = " ðŸ· "

[git_state]
disabled = false
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style = "bold yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_metrics]
disabled = false
added_style = "bold green"
deleted_style = "bold red"
only_nonzero_diffs = true
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = "="
ahead = "â‡¡"
behind = "â‡£"
diverged = "â‡•"
up_to_date = ""
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "Â»"
deleted = "âœ˜"
style = "bold red"

[golang]
disabled = true
symbol = "î˜§ "

[helm]
disabled = true

[hostname]
disabled = false
ssh_only = true
trim_at = ""
# trim_at = ".companyname.com"
format = "[$hostname]($style) in "
style = "bold dimmed green"

[java]
disabled = true
symbol = "î‰– "

[jobs]
disabled = true

[julia]
disabled = true
symbol = "î˜¤ "

[kotlin]
disabled = true

[kubernetes]
disabled = true

[line_break]
disabled = false

[lua]
disabled = true

[memory_usage]
disabled = true
symbol = "ï¡š "

[hg_branch]
disabled = true
symbol = "ï˜ "

[nim]
disabled = true
symbol = "ïš¤ "

[nix_shell]
disabled = true
symbol = "ï‹œ "

[nodejs]
disabled = false
format = "via [$symbol($version )]($style)"
version_format = "v${raw}"
symbol = "ï¢˜ "
detect_extensions = ["js", "mjs", "cjs", "ts"]
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]
style = "bold green"
not_capable_style = "bold red"

[ocaml]
disabled = true

[openstack]
disabled = true

[package]
disabled = false
format = "is [$symbol$version]($style) "
#symbol = "ðŸ“¦ "
symbol = "ï£– "
version_format = "v${raw}"
style = "bold 208"
display_private = false

[perl]
disabled = true
symbol = "î© "

[php]
disabled = true
symbol = "î˜ˆ "

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
disabled = false
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = "v${raw}"
#symbol = "ðŸ "
symbol = "î˜† "
style = "green bold"
#pyenv_version_name = false
pyenv_version_name = true
pyenv_prefix = "pyenv "
python_binary = ["python", "python3", "python2"]
detect_extensions = ["py"]
detect_files = [".python-version", "Pipfile", "__init__.py", "pyproject.toml", "requirements.txt", "setup.py", "tox.ini"]
detect_folders = []

[rlang]
disabled = true

[red]
disabled = true

[ruby]
disabled = true
symbol = "îˆ¾ "

[rust]
disabled = true
symbol = "îž¨ "

[scala]
disabled = true
symbol = "îœ· "

[shell]
disabled = true

# https://starship.rs/config/#shlvl
[shlvl]
disabled = true
symbol = "ï„  "

[singularity]
disabled = true

# https://starship.rs/config/#status
#[status]
#disabled = false
#format = "[$symbol $status]($style) "
#symbol = "âœ–"
#success_symbol = "âœ”ï¸"
#not_executable_symbol = "ðŸš«"
#not_found_symbol = "ðŸ”"
#sigint_symbol = "ðŸ§±"
#signal_symbol = "âš¡"
#style = "bold red"
#recognize_signal_code = true
#map_symbol = false
#pipestatus = false
#pipestatus_separator = "|"
#pipestatus_format = "\\[$pipestatus\\] => [$symbol$common_meaning$signal_name$maybe_int]($style)"

[swift]
disabled = true
symbol = "ï¯£ "

[terraform]
disabled = true

[time]
disabled = false
format = "[$time]($style) "
use_12hr = false
time_format = "%H:%M:%S:%3f"
style = "bold yellow"
utc_time_offset = "local"

[username]
disabled = false
style_root = "bold red"
style_user = "bold yellow"
format = "[$user]($style) in "
show_always = true

[vagrant]
disabled = true

[vlang]
disabled = true

# https://starship.rs/config/#vcsh
[vcsh]
disabled = true

[zig]
disabled = true
